apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol01
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /k8s
    server: clh-nfs.cloudra.local
  persistentVolumeReclaimPolicy: Recycle 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pod-nfs-data
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi 
