apiVersion: v1
kind: Pod
metadata:
  name: test-dtr
spec:
  containers:
    - name: uses-private-image
      image: clh-dtr.cloudra.local/admin/alpine:3.4
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
