apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv01
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /k8s
    server: clh-nfs.cloudra.local
  persistentVolumeReclaimPolicy: Recycle 

