#
# By mounting a specific claim one can attach to an existing volume, but the claim must exist
#

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: storage-pod
spec:
  selector:
    matchLabels:
      app: storage-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-pod
    spec:
      volumes:
      - name: curlpod-data
        persistentVolumeClaim:
          claimName: nfs-pvc1

      containers:
      - name: storage-pod
        command:
        - sh
        - -c
        - while true; do sleep 1; done
        image: radial/busyboxplus:curl
        volumeMounts:
        - mountPath: /tmp/foo
          name: curlpod-data
