apiVersion: v1
kind: Pod
metadata:
  name: curlpod
  labels:
    app: curlpod
spec:
  containers:
  - name: busybox
    image: yauritux/busybox-curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
